spring:
  application:
    name: morlatjanghak

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:20000/scholarship?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: scholarship
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
